name: Validar Entrega de Estudiantes

on:
  pull_request:
    branches: [ semestre3 ]

jobs:
  validar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout rama del PR (Estudiante)
        uses: actions/checkout@v4
        with:
          path: repo_estudiante

      - name: Checkout rama base (Tu rama semestre3)
        uses: actions/checkout@v4
        with:
          ref: semestre3
          path: repo_original

      - name: Preparar archivos para comparación
        run: |
          cp repo_estudiante/apps.json apps.json
          cp repo_estudiante/validar_json.py validar_json.py
          cp repo_original/apps.json apps_original.json

      - name: Ejecutar Validación
        run: python validar_json.py